### ISSUE TITLE
Tracking issue: Features for Blitz

### ISSUE THREAD

**Issue by nicoburns** [linebender/parley#208]
This issue track features that Blitz needs from Parley

### Parley features
- [x] Inline boxes
- [x] Tree-based styles
- [x] Whitespace collapsing
- [ ] Hit testing for inline spans
- [ ] Bounding boxes for inline spans
- [ ] Production grade shaping
- [ ] Floated boxes
- [ ] Vertical align style
- [ ] Text wrapping style
- [ ] White-space collapsing style
- [ ] Margin/border/padding for inline spans (should be bidi-aware)

Fontique
- [ ] Webfonts: Ability to customise name and attributes used for matching when loading a font
- [ ] Webfonts: The ability to remove/unload fonts
- [ ] More easily reuse system-fonts across collections (currently only possible by cloning)
